### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by sourcesoft** [Drawbotics/react-apollo-redux#1]
Hello, when using with Next.js
```
import React from 'react'
import { graphql } from 'react-apollo-redux'
import gql from 'graphql-tag'

import PostVoteButton from './PostVoteButton'

function PostVoteDown({ downvote, votes, id }) {
  return (
    <PostVoteButton
      className="downvote"
      onClickHandler={() => downvote({ variables: { id, votes: votes - 1 } })}
    />
  )
}

const downvotePost = gql`
  mutation updatePost($id: ID!, $votes: Int) {
    updatePost(id: $id, votes: $votes) {
      id
      votes
    }
  }
`

export default graphql(downvotePost, {
  name: 'downvote'
})(PostVoteDown)
```
error:
```
regeneratorRuntime is not defined
ReferenceError: regeneratorRuntime is not defined
    at o.value (http://localhost:3000/_next/1517886914795/page/blog/entry.js:30338:2252)
    at o.value (http://localhost:3000/_next/1517886914795/page/blog/entry.js:30338:1692)
    at finishClassComponent (http://localhost:3000/_next/1517886914795/commons.js:7879:31)
    at updateClassComponent (http://localhost:3000/_next/1517886914795/commons.js:7856:12)
    at beginWork (http://localhost:3000/_next/1517886914795/commons.js:8231:16)
    at performUnitOfWork (http://localhost:3000/_next/1517886914795/commons.js:10230:16)
    at workLoop (http://localhost:3000/_next/1517886914795/commons.js:10294:26)
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/1517886914795/commons.js:548:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/_next/1517886914795/commons.js:587:16)
    at invokeGuardedCallback (http://localhost:3000/_next/1517886914795/commons.js:444:27)
```

I think there's a conflict with babel polyfill and nextjs babel config or something?

**Comment by nicmosc** [comment]
It looks like it's an issue related to babel-polyfill. You need to import it at the top of your main `.js` file
```
import 'babel-polyfill';
```
There are other ways to enable polyfill with Next.js, such as in the `.babelrc` config but they don't seem to work.

This is a working solution for now. 

Here's a simple example using what you posted: https://gist.github.com/nicmosc/c5cdd3c4904de38c9d862d511c01abd5

**Comment by sourcesoft** [comment]
The pipeline operator is the one Nextjs doesn't support, replaced [them](https://github.com/Drawbotics/react-apollo-redux/blob/master/src/index.js#L30) with old syntax and it's working again
```
type: prefix + (options.name |> snakeCase |> toUpper)
```
to
```
type: prefix + (toUpper( snakeCase(options.name) ))
```

I think it's better to omit a proposal syntax for a library. Also there shouldn't be polyfills like babel (huge size), we better transform code instead of including polyfills in libraries.

**Comment by larsbs** [comment]
That's strange, the library is first transpiled using babel and then minified, so there shouldn't be any problems with the syntax since it's gonna be compiled to ES5. The only problem you can have is for those functions that can't be simply transpiled and that's when you need a polyfill.

I don't see any of those unsupported methods there so I don't know how there could be a problem with that transpiled code. I'm sure the problem is more related to using `async/await` in the code which needs the `reneratorRuntime`, than to the pipeline operator.

You're welcome to create a PR to replace `async/await` with promises (https://github.com/Drawbotics/react-apollo-redux/blob/master/src/index.js#L28) and we'll gladly accept it 😄

**Comment by larsbs** [comment]
Closing for inactivity
